//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TEF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TestAccRecord
    {
        public int Id { get; set; }
        public string Dt { get; set; }
        public string Ct { get; set; }
        public string Desc { get; set; }
        public Nullable<int> SubjectId { get; set; }
        public string Answers { get; set; }
        public string CorrectAnswer { get; set; }
    
        public virtual TestsDesc TestsDesc { get; set; }
    }
}
